
import java.awt.Image;
import java.io.File;
import java.lang.reflect.Field;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class DrinksMenu extends javax.swing.JFrame {
    
    DefaultListModel drinksM = new DefaultListModel();
    
    public DefaultListModel<String> drinks ;
    public DefaultListModel<String> meals;
    
    public ArrayList<Meal> meal;
    public ArrayList<Drinks> drink;
    
    private String UserName;

    public DrinksMenu(DefaultListModel<String> drinks, DefaultListModel<String> meals, ArrayList<Meal> meal, ArrayList<Drinks> drink, String UserName) {
        this.drinks = drinks;
        this.meals = meals;
        this.meal = meal;
        this.drink = drink;
        this.UserName = UserName;
        
        initComponents();
        initList();
        
        
    }

   
    
    
    
    /*
    ImageIcon beer = new ImageIcon(getClass().getClassLoader().getResource("images/beer.png"));
    ImageIcon cola = new ImageIcon(getClass().getClassLoader().getResource("images/cola.png"));
    ImageIcon mojito = new ImageIcon(getClass().getClassLoader().getResource("images/mojito.jpg"));
    ImageIcon tea = new ImageIcon(getClass().getClassLoader().getResource("images/tea.png"));
    ImageIcon coffee = new ImageIcon(getClass().getClassLoader().getResource("images/coffee.png"));
    */
    File beer = new File(this.getClass().getResource("/beer.png").getFile());
    File cola = new File(this.getClass().getResource("/cola.png").getFile());
    File mojito = new File(this.getClass().getResource("/mojito.png").getFile());
    File tea = new File(this.getClass().getResource("/tea.png").getFile());
    File coffee = new File(this.getClass().getResource("/coffee.png").getFile());
    
    
    /**
     * Creates new form UserControl
     */
    public DrinksMenu() {
        initComponents();
        initList();
    }
    
    private void initList(){
        //System.out.println(image.getAbsolutePath());
        drinksM.clear();
        
        drinksM.addElement(new MenuModel("Tea","Warm, traditional tea", 4.75, new ImageIcon(tea.getAbsolutePath())));
        drinksM.addElement(new MenuModel("Beer","Cold Dutch Beer", 14.2, new ImageIcon(beer.getAbsolutePath())));
        drinksM.addElement(new MenuModel("Coffee","It's time to wake up", 10, new ImageIcon(coffee.getAbsolutePath())));
        drinksM.addElement(new MenuModel("Mojito","Cool, Fresh drink", 16, new ImageIcon(mojito.getAbsolutePath())));
        drinksM.addElement(new MenuModel("Cola","It's just cola", 5, new ImageIcon(cola.getAbsolutePath())));
        
        jList1.setCellRenderer(new Renderer());
        jList1.setModel(drinksM);
    }
    
    void initPrices(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meals ");
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        addMenu.setText("Add to Menu");
        addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuActionPerformed
        // TODO add your handling code here:
        if(jList1.getSelectedValue()!=null)
        {
            int model = jList1.getSelectedIndex();
            MenuModel drinkItem = (MenuModel) drinksM.getElementAt(model);
            drinks.addElement(drinkItem.getName());
            drink.add(new Drinks(drinkItem.getName(), drinkItem.getDescription(), drinkItem.getPrice()));
            UserCont cont = new UserCont(drinks, meals, meal, drink,this.UserName);
            cont.setVisible(true);
            
            this.dispose();
                        
            
            
            
           
            /*
            UserCont cont = new UserCont();
            cont.drink = new Drinks(drinkItem.getName(), drinkItem.getDescription(), drinkItem.getPrice());
            cont.drinks.addElement(cont.drink.getName());
            */
            System.out.println(drinkItem.getName());
            
            
           // Object menuModel = model.getElementAt(jList1.getSelectedIndex());
            
            /*
            UserCont cont = new UserCont();
            Field field;
            try {
                field = menuModel.getClass().getDeclaredField("name");
                cont.drinks.addElement(field.toString());
                System.out.println(field.toString());
                
            } catch (NoSuchFieldException ex) {
                Logger.getLogger(DrinksMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SecurityException ex) {
                Logger.getLogger(DrinksMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
            
        }
    }//GEN-LAST:event_addMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrinksMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrinksMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrinksMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrinksMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrinksMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenu;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
