
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class MealsMenu extends javax.swing.JFrame {
    
    DefaultListModel mealsM = new DefaultListModel();
    
    public DefaultListModel<String> drinks ;
    public DefaultListModel<String> meals;
    
    public ArrayList<Meal> meal;
    public ArrayList<Drinks> drink;
    
    private String UserName;
    
    String Menemen = "Quick breakfast item of scrambled eggs cooked in sauteed vegetables";
    String Lahmacun = "Flat and crispy, Lahmacun is like a pizza served with a topping of minced meat, salad and lemon "
            + "juice on bread and can be wrapped, folded in half, or pulled apart to eat." ;
    String Iskender = "It is just another traditional Turkish way of serving döner";
    String Kebap = " wrapped in lavaş bread and topped "
                + "with yogurt and tomato sauce), and şiş (skewered and grilled seasoned cubes "
                + "of lamb or chicken meat).";
    String KuzuTandir = "Extremely tender meat and"
                + " served with iç pilav (rice with nuts, diced liver and currants).";
    
    File menemen = new File(this.getClass().getResource("/menemen.png").getFile());
    File lahmacun = new File(this.getClass().getResource("/lahmacun.png").getFile());
    File kuzutandir = new File(this.getClass().getResource("/kuzutandir.png").getFile());
    File kebap = new File(this.getClass().getResource("/kebap.png").getFile());
    File iskender = new File(this.getClass().getResource("/iskender.png").getFile());

    public MealsMenu(DefaultListModel<String> drinks, DefaultListModel<String> meals, ArrayList<Meal> meal, ArrayList<Drinks> drink,String UserName) {
        this.drinks = drinks;
        this.meals = meals;
        this.meal = meal;
        this.drink = drink;
        this.UserName = UserName;
        
        initComponents();
        initList();
    }
    
    
    
    /**
     * Creates new form MealsMenu
     */
    public MealsMenu() {
        initComponents();
        initList();
    }
    
    private void initList(){
        //System.out.println(image.getAbsolutePath());
        mealsM.clear();
        
        mealsM.addElement(new MenuModel("Menemen",Menemen, 25, new ImageIcon(menemen.getAbsolutePath())));
        mealsM.addElement(new MenuModel("Lahmacun",Lahmacun, 20, new ImageIcon(lahmacun.getAbsolutePath())));
        mealsM.addElement(new MenuModel("İskender",Iskender, 45, new ImageIcon(iskender.getAbsolutePath())));
        mealsM.addElement(new MenuModel("Kebap",Kebap, 35, new ImageIcon(kebap.getAbsolutePath())));
        mealsM.addElement(new MenuModel("Kuzu Tandır",KuzuTandir, 60, new ImageIcon(kuzutandir.getAbsolutePath())));
        
        jList1.setCellRenderer(new Renderer());
        jList1.setModel(mealsM);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        addMenu.setText("Add to Menu");
        addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuActionPerformed
        // TODO add your handling code here:
        if(jList1.getSelectedValue()!=null)
        {
            int model = jList1.getSelectedIndex();
            MenuModel mealItem = (MenuModel) mealsM.getElementAt(model);
            meals.addElement(mealItem.getName());
            meal.add(new Meal(mealItem.getName(), mealItem.getDescription(), mealItem.getPrice()));
            UserCont cont = new UserCont(drinks, meals, meal, drink, this.UserName);
            cont.setVisible(true);
            
            this.dispose();
        }

    }//GEN-LAST:event_addMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MealsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MealsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MealsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MealsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MealsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenu;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
